import type { ActivityInput, AvatarData } from '@vers/idle-core';
import { ActivityFailureAction, ActivityType, EquipmentSlot } from '@vers/idle-core';
import type { ReplaySimulationActivitySource } from './types';

/**
 * Builds the engine's `ActivityInput`/`AvatarData` a replay drives, from the activity's stamped
 * seed and build snapshot — the only simulation inputs the current schema persists. Every replay
 * drives the same placeholder encounter and weapon until a node-content service and avatar
 * equipment persistence exist to author real ones; honest test fixtures are generated by running
 * this same engine against its own output, so a cache-miss rebuild reproduces byte-identical
 * checkpoints to the original run. `failureAction` is always `Abort`: a real persisted stream's
 * first terminal checkpoint (`Failed` or `Completed`) ends the activity's append-ability regardless
 * of the failure action stamped on it, so a driver ever asked to `Retry`-and-continue past one would
 * be reproducing a stream shape the server can never actually hold. Returns fresh placeholder
 * enemy/weapon objects on every call: the engine mutates its input in place, so a caller running
 * several replay jobs from one shared literal would have them corrupt each other.
 */
export function buildReplaySimulationInput(activity: Readonly<ReplaySimulationActivitySource>): {
  activity: ActivityInput;
  avatar: AvatarData;
} {
  return {
    activity: {
      difficulty: 1,
      enemies: [buildPlaceholderEnemy()],
      failureAction: ActivityFailureAction.Abort,
      id: activity.id,
      name: 'World Map Encounter',
      seed: activity.seed,
      type: ActivityType.WorldMapEncounter,
    },
    avatar: {
      id: activity.avatarID,
      level: activity.buildSnapshot.level,
      life: PLACEHOLDER_AVATAR_LIFE,
      name: activity.avatarID,
      paperdoll: { [EquipmentSlot.MainHand]: buildPlaceholderWeapon() },
      xp: activity.buildSnapshot.xp,
    },
  };
}

function buildPlaceholderEnemy() {
  return {
    level: 1,
    life: 30,
    name: 'World Map Enemy',
    primaryAttack: { maxDamage: 3, minDamage: 1, speed: 0.5 },
    xp: 10,
  };
}

const PLACEHOLDER_AVATAR_LIFE = 200;

function buildPlaceholderWeapon() {
  return {
    id: 'placeholder_weapon',
    maxDamage: 20,
    minDamage: 10,
    name: 'Placeholder Blade',
    speed: 0.8,
  };
}
