/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type ActivityStatus =
  | 'active'
  | 'capped'
  | 'parked'
  | 'quarantined'
  | 'rejected'
  | 'stopped';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VerificationType = '2fa' | '2fa-setup' | 'change-email' | 'onboarding';

export interface Activities {
  appendedAt: Timestamp | null;
  appendedHead: Generated<number>;
  appendedTimeMs: Generated<Int8>;
  avatarId: string;
  buildSnapshot: import('./types').Json;
  contentVersion: string;
  createdAt: Generated<Timestamp>;
  id: string;
  keyVersion: Generated<number>;
  lastHash: string;
  replayAttempts: Generated<number>;
  scopeId: string;
  scopeType: string;
  seed: string;
  simVersion: string;
  startChainIndex: Generated<number>;
  startedAt: Generated<Timestamp>;
  startHash: string;
  status: Generated<ActivityStatus>;
  stoppedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedHead: Generated<number>;
  writerSessionId: string | null;
}

export interface ActivityChains {
  appendedChainIndex: Generated<number>;
  appendedNextSeed: string;
  avatarId: string;
  createdAt: Generated<Timestamp>;
  genesisSeed: string;
  priority: Generated<number>;
  scopeId: string;
  scopeType: string;
  verifiedChainIndex: Generated<number>;
  verifiedNextSeed: string;
}

export interface ActivityCheckpoints {
  activityId: string;
  appendedAt: Generated<Timestamp>;
  hash: string;
  payload: import('./types').Json;
  prevHash: string;
  version: number;
}

export interface AvatarGrants {
  avatarId: string;
  createdAt: Generated<Timestamp>;
  key: string;
  kind: string;
}

export interface Avatars {
  createdAt: Generated<Timestamp>;
  id: string;
  level: Generated<number>;
  name: string;
  simBudgetMs: Generated<Int8>;
  simMeteredAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  xp: Generated<number>;
}

export interface ConsumedTransactionTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  jti: string;
}

export interface PendingTransactions {
  action: string;
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string;
  sessionId: string | null;
  target: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string;
  previousRefreshToken: string | null;
  refreshToken: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  verified: Generated<boolean>;
}

export interface SimVersions {
  bunVersion: string;
  createdAt: Generated<Timestamp>;
  deployedAt: Generated<Timestamp>;
  engineHash: string;
  imageRef: string;
  providerUrl: string;
  retainedUntil: Timestamp;
  status: Generated<string>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  passwordHash: string | null;
  passwordResetToken: string | null;
  passwordResetTokenExpiresAt: Timestamp | null;
  seed: Generated<number>;
  updatedAt: Generated<Timestamp>;
  username: string;
}

export interface Verifications {
  algorithm: string;
  charSet: string;
  createdAt: Generated<Timestamp>;
  digits: number;
  expiresAt: Timestamp | null;
  id: string;
  lastVerifiedAt: Timestamp | null;
  lastVerifiedCode: string | null;
  period: number;
  secret: string;
  target: string;
  type: VerificationType;
}

export interface DB {
  activities: Activities;
  activityChains: ActivityChains;
  activityCheckpoints: ActivityCheckpoints;
  avatarGrants: AvatarGrants;
  avatars: Avatars;
  consumedTransactionTokens: ConsumedTransactionTokens;
  pendingTransactions: PendingTransactions;
  sessions: Sessions;
  simVersions: SimVersions;
  users: Users;
  verifications: Verifications;
}
