/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type ActivityStatus = 'active' | 'capped' | 'quarantined' | 'rejected' | 'stopped';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = Array<JsonValue>;

export interface JsonObject {
  [x: string]: JsonValue | undefined;
}

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VerificationType = '2fa' | '2fa-setup' | 'change-email' | 'onboarding';

export interface Activities {
  appendedAt: Timestamp | null;
  appendedHead: Generated<number>;
  avatarId: string;
  buildSnapshot: Json;
  contentVersion: string;
  createdAt: Generated<Timestamp>;
  id: string;
  lastHash: string;
  nodeId: string;
  seed: string;
  simVersion: string;
  startChainIndex: Generated<number>;
  startedAt: Generated<Timestamp>;
  startHash: string;
  status: Generated<ActivityStatus>;
  stoppedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  verifiedHead: Generated<number>;
}

export interface ActivityChains {
  appendedChainIndex: Generated<number>;
  appendedNextSeed: string;
  avatarId: string;
  createdAt: Generated<Timestamp>;
  genesisSeed: string;
  nodeId: string;
  verifiedChainIndex: Generated<number>;
  verifiedNextSeed: string;
}

export interface ActivityCheckpoints {
  activityId: string;
  appendedAt: Generated<Timestamp>;
  hash: string;
  payload: Json;
  prevHash: string;
  version: number;
}

export interface Avatars {
  createdAt: Generated<Timestamp>;
  id: string;
  level: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  xp: Generated<number>;
}

export interface ConsumedTransactionTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  jti: string;
}

export interface PendingTransactions {
  action: string;
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string;
  sessionId: string | null;
  target: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string;
  previousRefreshToken: string | null;
  refreshToken: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  verified: Generated<boolean>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  passwordHash: string | null;
  passwordResetToken: string | null;
  passwordResetTokenExpiresAt: Timestamp | null;
  seed: Generated<number>;
  updatedAt: Generated<Timestamp>;
  username: string;
}

export interface Verifications {
  algorithm: string;
  charSet: string;
  createdAt: Generated<Timestamp>;
  digits: number;
  expiresAt: Timestamp | null;
  id: string;
  lastVerifiedAt: Timestamp | null;
  lastVerifiedCode: string | null;
  period: number;
  secret: string;
  target: string;
  type: VerificationType;
}

export interface DB {
  activities: Activities;
  activityChains: ActivityChains;
  activityCheckpoints: ActivityCheckpoints;
  avatars: Avatars;
  consumedTransactionTokens: ConsumedTransactionTokens;
  pendingTransactions: PendingTransactions;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
