// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export function getDashboard(
  args: GetDashboardArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetDashboardResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getDashboard:getDashboard',
    {
      uid: args.uid,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDashboard.
 */
export interface GetDashboardArgs {
  uid: string;
}

/**
 * A collection of values returned by getDashboard.
 */
export interface GetDashboardResult {
  readonly createdAt: string;
  readonly createdBy: string;
  readonly dashboard: string;
  readonly id: string;
  readonly uid: string;
  readonly updatedAt: string;
  readonly updatedBy: string;
  readonly version: number;
}
export function getDashboardOutput(
  args: GetDashboardOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDashboardResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getDashboard:getDashboard',
    {
      uid: args.uid,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDashboard.
 */
export interface GetDashboardOutputArgs {
  uid: pulumi.Input<string>;
}
