// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export function getDataset(
  args: GetDatasetArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetDatasetResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getDataset:getDataset',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDataset.
 */
export interface GetDatasetArgs {
  id: string;
}

/**
 * A collection of values returned by getDataset.
 */
export interface GetDatasetResult {
  readonly description: string;
  readonly edgeDeployment: string;
  readonly id: string;
  readonly kind: string;
  readonly mapFields: string[];
  readonly name: string;
  readonly retentionDays: number;
  readonly useRetentionPeriod: boolean;
}
export function getDatasetOutput(
  args: GetDatasetOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDatasetResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getDataset:getDataset',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getDataset.
 */
export interface GetDatasetOutputArgs {
  id: pulumi.Input<string>;
}
