// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export function getMonitor(
  args: GetMonitorArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetMonitorResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getMonitor:getMonitor',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getMonitor.
 */
export interface GetMonitorArgs {
  id: string;
}

/**
 * A collection of values returned by getMonitor.
 */
export interface GetMonitorResult {
  readonly alertOnNoData: boolean;
  readonly aplQuery: string;
  readonly compareDays: number;
  readonly createdAt: string;
  readonly createdBy: string;
  readonly delay: number;
  readonly description: string;
  readonly disabledUntil: string;
  readonly id: string;
  readonly intervalMinutes: number;
  readonly mplQuery: string;
  readonly name: string;
  readonly notifierIds: string[];
  readonly notifyByGroup: boolean;
  readonly notifyEveryRun: boolean;
  readonly operator: string;
  readonly rangeMinutes: number;
  readonly resolvable: boolean;
  readonly skipResolved: boolean;
  readonly threshold: number;
  readonly tolerance: number;
  readonly triggerAfterNPositiveResults: number;
  readonly triggerFromNRuns: number;
  readonly type: string;
}
export function getMonitorOutput(
  args: GetMonitorOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetMonitorResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getMonitor:getMonitor',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getMonitor.
 */
export interface GetMonitorOutputArgs {
  id: pulumi.Input<string>;
}
