// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from './types/input';
import * as outputs from './types/output';
import * as utilities from './utilities';

export function getNotifier(
  args: GetNotifierArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetNotifierResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getNotifier:getNotifier',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getNotifier.
 */
export interface GetNotifierArgs {
  id: string;
}

/**
 * A collection of values returned by getNotifier.
 */
export interface GetNotifierResult {
  readonly id: string;
  readonly name: string;
  readonly properties: outputs.GetNotifierProperties;
}
export function getNotifierOutput(
  args: GetNotifierOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetNotifierResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getNotifier:getNotifier',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getNotifier.
 */
export interface GetNotifierOutputArgs {
  id: pulumi.Input<string>;
}
