// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from './types/input';
import * as outputs from './types/output';
import * as utilities from './utilities';

export function getToken(args: GetTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetTokenResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getToken:getToken',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getToken.
 */
export interface GetTokenArgs {
  id: string;
}

/**
 * A collection of values returned by getToken.
 */
export interface GetTokenResult {
  readonly datasetCapabilities: { [key: string]: outputs.GetTokenDatasetCapabilities };
  readonly description: string;
  readonly expiresAt: string;
  readonly id: string;
  readonly name: string;
  readonly orgCapabilities: outputs.GetTokenOrgCapabilities;
  readonly rotationGracePeriod: string;
  readonly token: string;
}
export function getTokenOutput(
  args: GetTokenOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetTokenResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getToken:getToken',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getToken.
 */
export interface GetTokenOutputArgs {
  id: pulumi.Input<string>;
}
