// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getUser:getUser',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
  id: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
  readonly email: string;
  readonly id: string;
  readonly name: string;
  readonly role: string;
}
export function getUserOutput(
  args: GetUserOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetUserResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getUser:getUser',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
  id: pulumi.Input<string>;
}
