// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export function getVirtualField(
  args: GetVirtualFieldArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetVirtualFieldResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'axiom:index/getVirtualField:getVirtualField',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getVirtualField.
 */
export interface GetVirtualFieldArgs {
  id: string;
}

/**
 * A collection of values returned by getVirtualField.
 */
export interface GetVirtualFieldResult {
  readonly dataset: string;
  readonly description: string;
  readonly expression: string;
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly unit: string;
}
export function getVirtualFieldOutput(
  args: GetVirtualFieldOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetVirtualFieldResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'axiom:index/getVirtualField:getVirtualField',
    {
      id: args.id,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getVirtualField.
 */
export interface GetVirtualFieldOutputArgs {
  id: pulumi.Input<string>;
}
