// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

// Export members:
export { DashboardArgs, DashboardState } from './dashboard';
export type Dashboard = import('./dashboard').Dashboard;
export const Dashboard: typeof import('./dashboard').Dashboard = null as any;
utilities.lazyLoad(exports, ['Dashboard'], () => require('./dashboard'));

export { DatasetArgs, DatasetState } from './dataset';
export type Dataset = import('./dataset').Dataset;
export const Dataset: typeof import('./dataset').Dataset = null as any;
utilities.lazyLoad(exports, ['Dataset'], () => require('./dataset'));

export { GetDashboardArgs, GetDashboardResult, GetDashboardOutputArgs } from './getDashboard';
export const getDashboard: typeof import('./getDashboard').getDashboard = null as any;
export const getDashboardOutput: typeof import('./getDashboard').getDashboardOutput = null as any;
utilities.lazyLoad(exports, ['getDashboard', 'getDashboardOutput'], () =>
  require('./getDashboard'),
);

export { GetDatasetArgs, GetDatasetResult, GetDatasetOutputArgs } from './getDataset';
export const getDataset: typeof import('./getDataset').getDataset = null as any;
export const getDatasetOutput: typeof import('./getDataset').getDatasetOutput = null as any;
utilities.lazyLoad(exports, ['getDataset', 'getDatasetOutput'], () => require('./getDataset'));

export { GetMonitorArgs, GetMonitorResult, GetMonitorOutputArgs } from './getMonitor';
export const getMonitor: typeof import('./getMonitor').getMonitor = null as any;
export const getMonitorOutput: typeof import('./getMonitor').getMonitorOutput = null as any;
utilities.lazyLoad(exports, ['getMonitor', 'getMonitorOutput'], () => require('./getMonitor'));

export { GetNotifierArgs, GetNotifierResult, GetNotifierOutputArgs } from './getNotifier';
export const getNotifier: typeof import('./getNotifier').getNotifier = null as any;
export const getNotifierOutput: typeof import('./getNotifier').getNotifierOutput = null as any;
utilities.lazyLoad(exports, ['getNotifier', 'getNotifierOutput'], () => require('./getNotifier'));

export { GetTokenArgs, GetTokenResult, GetTokenOutputArgs } from './getToken';
export const getToken: typeof import('./getToken').getToken = null as any;
export const getTokenOutput: typeof import('./getToken').getTokenOutput = null as any;
utilities.lazyLoad(exports, ['getToken', 'getTokenOutput'], () => require('./getToken'));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from './getUser';
export const getUser: typeof import('./getUser').getUser = null as any;
export const getUserOutput: typeof import('./getUser').getUserOutput = null as any;
utilities.lazyLoad(exports, ['getUser', 'getUserOutput'], () => require('./getUser'));

export {
  GetVirtualFieldArgs,
  GetVirtualFieldResult,
  GetVirtualFieldOutputArgs,
} from './getVirtualField';
export const getVirtualField: typeof import('./getVirtualField').getVirtualField = null as any;
export const getVirtualFieldOutput: typeof import('./getVirtualField').getVirtualFieldOutput =
  null as any;
utilities.lazyLoad(exports, ['getVirtualField', 'getVirtualFieldOutput'], () =>
  require('./getVirtualField'),
);

export { MonitorArgs, MonitorState } from './monitor';
export type Monitor = import('./monitor').Monitor;
export const Monitor: typeof import('./monitor').Monitor = null as any;
utilities.lazyLoad(exports, ['Monitor'], () => require('./monitor'));

export { NotifierArgs, NotifierState } from './notifier';
export type Notifier = import('./notifier').Notifier;
export const Notifier: typeof import('./notifier').Notifier = null as any;
utilities.lazyLoad(exports, ['Notifier'], () => require('./notifier'));

export * from './provider';
import { Provider } from './provider';

export { TokenArgs, TokenState } from './token';
export type Token = import('./token').Token;
export const Token: typeof import('./token').Token = null as any;
utilities.lazyLoad(exports, ['Token'], () => require('./token'));

export { UserArgs, UserState } from './user';
export type User = import('./user').User;
export const User: typeof import('./user').User = null as any;
utilities.lazyLoad(exports, ['User'], () => require('./user'));

export { VirtualFieldArgs, VirtualFieldState } from './virtualField';
export type VirtualField = import('./virtualField').VirtualField;
export const VirtualField: typeof import('./virtualField').VirtualField = null as any;
utilities.lazyLoad(exports, ['VirtualField'], () => require('./virtualField'));

// Export sub-modules:
import * as config from './config';
import * as types from './types';

export { config, types };

const _module = {
  version: utilities.getVersion(),
  construct: (name: string, type: string, urn: string): pulumi.Resource => {
    switch (type) {
      case 'axiom:index/dashboard:Dashboard':
        return new Dashboard(name, <any>undefined, { urn });
      case 'axiom:index/dataset:Dataset':
        return new Dataset(name, <any>undefined, { urn });
      case 'axiom:index/monitor:Monitor':
        return new Monitor(name, <any>undefined, { urn });
      case 'axiom:index/notifier:Notifier':
        return new Notifier(name, <any>undefined, { urn });
      case 'axiom:index/token:Token':
        return new Token(name, <any>undefined, { urn });
      case 'axiom:index/user:User':
        return new User(name, <any>undefined, { urn });
      case 'axiom:index/virtualField:VirtualField':
        return new VirtualField(name, <any>undefined, { urn });
      default:
        throw new Error(`unknown resource type ${type}`);
    }
  },
};
pulumi.runtime.registerResourceModule('axiom', 'index/dashboard', _module);
pulumi.runtime.registerResourceModule('axiom', 'index/dataset', _module);
pulumi.runtime.registerResourceModule('axiom', 'index/monitor', _module);
pulumi.runtime.registerResourceModule('axiom', 'index/notifier', _module);
pulumi.runtime.registerResourceModule('axiom', 'index/token', _module);
pulumi.runtime.registerResourceModule('axiom', 'index/user', _module);
pulumi.runtime.registerResourceModule('axiom', 'index/virtualField', _module);
pulumi.runtime.registerResourcePackage('axiom', {
  version: utilities.getVersion(),
  constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
    if (type !== 'pulumi:providers:axiom') {
      throw new Error(`unknown provider type ${type}`);
    }
    return new Provider(name, <any>undefined, { urn });
  },
});
