// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class Monitor extends pulumi.CustomResource {
  /**
   * Get an existing Monitor resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: MonitorState,
    opts?: pulumi.CustomResourceOptions,
  ): Monitor {
    return new Monitor(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'axiom:index/monitor:Monitor';

  /**
   * Returns true if the given object is an instance of Monitor.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Monitor {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === Monitor.__pulumiType;
  }

  /**
   * If the monitor should trigger an alert if there is no data
   */
  declare public readonly alertOnNoData: pulumi.Output<boolean>;
  /**
   * The APL query used inside the monitor (mutually exclusive with mpl_query)
   */
  declare public readonly aplQuery: pulumi.Output<string | undefined>;
  /**
   * The number of days to compare for anomaly detection
   */
  declare public readonly compareDays: pulumi.Output<number>;
  /**
   * The timestamp when the monitor was created
   */
  declare public readonly /*out*/ createdAt: pulumi.Output<string>;
  /**
   * The ID of the user who created the monitor
   */
  declare public readonly /*out*/ createdBy: pulumi.Output<string>;
  /**
   * The delay in seconds before the monitor runs (useful for situations where data is batched/delayed)
   */
  declare public readonly delay: pulumi.Output<number>;
  /**
   * Monitor description
   */
  declare public readonly description: pulumi.Output<string | undefined>;
  /**
   * The time the monitor will be disabled until
   */
  declare public readonly disabledUntil: pulumi.Output<string | undefined>;
  /**
   * How often the monitor should run
   */
  declare public readonly intervalMinutes: pulumi.Output<number>;
  /**
   * The MPL query used inside the monitor (mutually exclusive with apl_query)
   */
  declare public readonly mplQuery: pulumi.Output<string | undefined>;
  /**
   * Monitor name
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * A list of notifier id's to be used when this monitor triggers
   */
  declare public readonly notifierIds: pulumi.Output<string[] | undefined>;
  /**
   * If the monitor should track non-time groups separately
   */
  declare public readonly notifyByGroup: pulumi.Output<boolean>;
  /**
   * Indicates whether to send notifications on every trigger
   */
  declare public readonly notifyEveryRun: pulumi.Output<boolean>;
  /**
   * Operator used in monitor trigger evaluation
   */
  declare public readonly operator: pulumi.Output<string>;
  /**
   * Query time range from now
   */
  declare public readonly rangeMinutes: pulumi.Output<number>;
  /**
   * Determines whether the events triggered by the monitor are individually resolvable. This has no effect on threshold monitors
   */
  declare public readonly resolvable: pulumi.Output<boolean>;
  /**
   * Specifies whether to skip resolved alerts
   */
  declare public readonly skipResolved: pulumi.Output<boolean>;
  /**
   * The threshold where the monitor should trigger
   */
  declare public readonly threshold: pulumi.Output<number>;
  /**
   * The tolerance percentage for anomaly detection
   */
  declare public readonly tolerance: pulumi.Output<number>;
  /**
   * The number of positive results needed before triggering
   */
  declare public readonly triggerAfterNPositiveResults: pulumi.Output<number>;
  /**
   * The number of consecutive check runs that must trigger before triggering an alert
   */
  declare public readonly triggerFromNRuns: pulumi.Output<number>;
  /**
   * The type of the monitor. Possible values include: 'Threshold', 'AnomalyDetection', 'MatchEvent'
   */
  declare public readonly type: pulumi.Output<string>;

  /**
   * Create a Monitor resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: MonitorArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: MonitorArgs | MonitorState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as MonitorState | undefined;
      resourceInputs['alertOnNoData'] = state?.alertOnNoData;
      resourceInputs['aplQuery'] = state?.aplQuery;
      resourceInputs['compareDays'] = state?.compareDays;
      resourceInputs['createdAt'] = state?.createdAt;
      resourceInputs['createdBy'] = state?.createdBy;
      resourceInputs['delay'] = state?.delay;
      resourceInputs['description'] = state?.description;
      resourceInputs['disabledUntil'] = state?.disabledUntil;
      resourceInputs['intervalMinutes'] = state?.intervalMinutes;
      resourceInputs['mplQuery'] = state?.mplQuery;
      resourceInputs['name'] = state?.name;
      resourceInputs['notifierIds'] = state?.notifierIds;
      resourceInputs['notifyByGroup'] = state?.notifyByGroup;
      resourceInputs['notifyEveryRun'] = state?.notifyEveryRun;
      resourceInputs['operator'] = state?.operator;
      resourceInputs['rangeMinutes'] = state?.rangeMinutes;
      resourceInputs['resolvable'] = state?.resolvable;
      resourceInputs['skipResolved'] = state?.skipResolved;
      resourceInputs['threshold'] = state?.threshold;
      resourceInputs['tolerance'] = state?.tolerance;
      resourceInputs['triggerAfterNPositiveResults'] = state?.triggerAfterNPositiveResults;
      resourceInputs['triggerFromNRuns'] = state?.triggerFromNRuns;
      resourceInputs['type'] = state?.type;
    } else {
      const args = argsOrState as MonitorArgs | undefined;
      if (args?.type === undefined && !opts.urn) {
        throw new Error("Missing required property 'type'");
      }
      resourceInputs['alertOnNoData'] = args?.alertOnNoData;
      resourceInputs['aplQuery'] = args?.aplQuery;
      resourceInputs['compareDays'] = args?.compareDays;
      resourceInputs['delay'] = args?.delay;
      resourceInputs['description'] = args?.description;
      resourceInputs['disabledUntil'] = args?.disabledUntil;
      resourceInputs['intervalMinutes'] = args?.intervalMinutes;
      resourceInputs['mplQuery'] = args?.mplQuery;
      resourceInputs['name'] = args?.name;
      resourceInputs['notifierIds'] = args?.notifierIds;
      resourceInputs['notifyByGroup'] = args?.notifyByGroup;
      resourceInputs['notifyEveryRun'] = args?.notifyEveryRun;
      resourceInputs['operator'] = args?.operator;
      resourceInputs['rangeMinutes'] = args?.rangeMinutes;
      resourceInputs['resolvable'] = args?.resolvable;
      resourceInputs['skipResolved'] = args?.skipResolved;
      resourceInputs['threshold'] = args?.threshold;
      resourceInputs['tolerance'] = args?.tolerance;
      resourceInputs['triggerAfterNPositiveResults'] = args?.triggerAfterNPositiveResults;
      resourceInputs['triggerFromNRuns'] = args?.triggerFromNRuns;
      resourceInputs['type'] = args?.type;
      resourceInputs['createdAt'] = undefined /*out*/;
      resourceInputs['createdBy'] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Monitor.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Monitor resources.
 */
export interface MonitorState {
  /**
   * If the monitor should trigger an alert if there is no data
   */
  alertOnNoData?: pulumi.Input<boolean | undefined>;
  /**
   * The APL query used inside the monitor (mutually exclusive with mpl_query)
   */
  aplQuery?: pulumi.Input<string | undefined>;
  /**
   * The number of days to compare for anomaly detection
   */
  compareDays?: pulumi.Input<number | undefined>;
  /**
   * The timestamp when the monitor was created
   */
  createdAt?: pulumi.Input<string | undefined>;
  /**
   * The ID of the user who created the monitor
   */
  createdBy?: pulumi.Input<string | undefined>;
  /**
   * The delay in seconds before the monitor runs (useful for situations where data is batched/delayed)
   */
  delay?: pulumi.Input<number | undefined>;
  /**
   * Monitor description
   */
  description?: pulumi.Input<string | undefined>;
  /**
   * The time the monitor will be disabled until
   */
  disabledUntil?: pulumi.Input<string | undefined>;
  /**
   * How often the monitor should run
   */
  intervalMinutes?: pulumi.Input<number | undefined>;
  /**
   * The MPL query used inside the monitor (mutually exclusive with apl_query)
   */
  mplQuery?: pulumi.Input<string | undefined>;
  /**
   * Monitor name
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * A list of notifier id's to be used when this monitor triggers
   */
  notifierIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * If the monitor should track non-time groups separately
   */
  notifyByGroup?: pulumi.Input<boolean | undefined>;
  /**
   * Indicates whether to send notifications on every trigger
   */
  notifyEveryRun?: pulumi.Input<boolean | undefined>;
  /**
   * Operator used in monitor trigger evaluation
   */
  operator?: pulumi.Input<string | undefined>;
  /**
   * Query time range from now
   */
  rangeMinutes?: pulumi.Input<number | undefined>;
  /**
   * Determines whether the events triggered by the monitor are individually resolvable. This has no effect on threshold monitors
   */
  resolvable?: pulumi.Input<boolean | undefined>;
  /**
   * Specifies whether to skip resolved alerts
   */
  skipResolved?: pulumi.Input<boolean | undefined>;
  /**
   * The threshold where the monitor should trigger
   */
  threshold?: pulumi.Input<number | undefined>;
  /**
   * The tolerance percentage for anomaly detection
   */
  tolerance?: pulumi.Input<number | undefined>;
  /**
   * The number of positive results needed before triggering
   */
  triggerAfterNPositiveResults?: pulumi.Input<number | undefined>;
  /**
   * The number of consecutive check runs that must trigger before triggering an alert
   */
  triggerFromNRuns?: pulumi.Input<number | undefined>;
  /**
   * The type of the monitor. Possible values include: 'Threshold', 'AnomalyDetection', 'MatchEvent'
   */
  type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Monitor resource.
 */
export interface MonitorArgs {
  /**
   * If the monitor should trigger an alert if there is no data
   */
  alertOnNoData?: pulumi.Input<boolean | undefined>;
  /**
   * The APL query used inside the monitor (mutually exclusive with mpl_query)
   */
  aplQuery?: pulumi.Input<string | undefined>;
  /**
   * The number of days to compare for anomaly detection
   */
  compareDays?: pulumi.Input<number | undefined>;
  /**
   * The delay in seconds before the monitor runs (useful for situations where data is batched/delayed)
   */
  delay?: pulumi.Input<number | undefined>;
  /**
   * Monitor description
   */
  description?: pulumi.Input<string | undefined>;
  /**
   * The time the monitor will be disabled until
   */
  disabledUntil?: pulumi.Input<string | undefined>;
  /**
   * How often the monitor should run
   */
  intervalMinutes?: pulumi.Input<number | undefined>;
  /**
   * The MPL query used inside the monitor (mutually exclusive with apl_query)
   */
  mplQuery?: pulumi.Input<string | undefined>;
  /**
   * Monitor name
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * A list of notifier id's to be used when this monitor triggers
   */
  notifierIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * If the monitor should track non-time groups separately
   */
  notifyByGroup?: pulumi.Input<boolean | undefined>;
  /**
   * Indicates whether to send notifications on every trigger
   */
  notifyEveryRun?: pulumi.Input<boolean | undefined>;
  /**
   * Operator used in monitor trigger evaluation
   */
  operator?: pulumi.Input<string | undefined>;
  /**
   * Query time range from now
   */
  rangeMinutes?: pulumi.Input<number | undefined>;
  /**
   * Determines whether the events triggered by the monitor are individually resolvable. This has no effect on threshold monitors
   */
  resolvable?: pulumi.Input<boolean | undefined>;
  /**
   * Specifies whether to skip resolved alerts
   */
  skipResolved?: pulumi.Input<boolean | undefined>;
  /**
   * The threshold where the monitor should trigger
   */
  threshold?: pulumi.Input<number | undefined>;
  /**
   * The tolerance percentage for anomaly detection
   */
  tolerance?: pulumi.Input<number | undefined>;
  /**
   * The number of positive results needed before triggering
   */
  triggerAfterNPositiveResults?: pulumi.Input<number | undefined>;
  /**
   * The number of consecutive check runs that must trigger before triggering an alert
   */
  triggerFromNRuns?: pulumi.Input<number | undefined>;
  /**
   * The type of the monitor. Possible values include: 'Threshold', 'AnomalyDetection', 'MatchEvent'
   */
  type: pulumi.Input<string>;
}
