// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from './types/input';
import * as outputs from './types/output';
import * as utilities from './utilities';

export class Token extends pulumi.CustomResource {
  /**
   * Get an existing Token resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: TokenState,
    opts?: pulumi.CustomResourceOptions,
  ): Token {
    return new Token(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'axiom:index/token:Token';

  /**
   * Returns true if the given object is an instance of Token.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Token {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === Token.__pulumiType;
  }

  /**
   * The capabilities available to the token for each dataset
   */
  declare public readonly datasetCapabilities: pulumi.Output<{
    [key: string]: outputs.TokenDatasetCapabilities;
  }>;
  /**
   * The description of the token
   */
  declare public readonly description: pulumi.Output<string | undefined>;
  /**
   * The time when the token expires. If not set, the token will not expire. Must be in RFC3339 format
   */
  declare public readonly expiresAt: pulumi.Output<string | undefined>;
  /**
   * The name of the token
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * The organisation capabilities available to the token
   */
  declare public readonly orgCapabilities: pulumi.Output<outputs.TokenOrgCapabilities | undefined>;
  /**
   * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
   * How long the previous token remains valid when this token is regenerated during an update (for example: 30s, 5m, 1h). Defaults to 48h when omitted.
   */
  declare public readonly rotationGracePeriod: pulumi.Output<string | undefined>;
  /**
   * The token value to be used in API calls
   */
  declare public readonly /*out*/ token: pulumi.Output<string>;

  /**
   * Create a Token resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args?: TokenArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: TokenArgs | TokenState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as TokenState | undefined;
      resourceInputs['datasetCapabilities'] = state?.datasetCapabilities;
      resourceInputs['description'] = state?.description;
      resourceInputs['expiresAt'] = state?.expiresAt;
      resourceInputs['name'] = state?.name;
      resourceInputs['orgCapabilities'] = state?.orgCapabilities;
      resourceInputs['rotationGracePeriod'] = state?.rotationGracePeriod;
      resourceInputs['token'] = state?.token;
    } else {
      const args = argsOrState as TokenArgs | undefined;
      resourceInputs['datasetCapabilities'] = args?.datasetCapabilities;
      resourceInputs['description'] = args?.description;
      resourceInputs['expiresAt'] = args?.expiresAt;
      resourceInputs['name'] = args?.name;
      resourceInputs['orgCapabilities'] = args?.orgCapabilities;
      resourceInputs['rotationGracePeriod'] = args?.rotationGracePeriod
        ? pulumi.secret(args.rotationGracePeriod)
        : undefined;
      resourceInputs['token'] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ['rotationGracePeriod', 'token'] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Token.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Token resources.
 */
export interface TokenState {
  /**
   * The capabilities available to the token for each dataset
   */
  datasetCapabilities?: pulumi.Input<
    { [key: string]: pulumi.Input<inputs.TokenDatasetCapabilities> } | undefined
  >;
  /**
   * The description of the token
   */
  description?: pulumi.Input<string | undefined>;
  /**
   * The time when the token expires. If not set, the token will not expire. Must be in RFC3339 format
   */
  expiresAt?: pulumi.Input<string | undefined>;
  /**
   * The name of the token
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * The organisation capabilities available to the token
   */
  orgCapabilities?: pulumi.Input<inputs.TokenOrgCapabilities | undefined>;
  /**
   * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
   * How long the previous token remains valid when this token is regenerated during an update (for example: 30s, 5m, 1h). Defaults to 48h when omitted.
   */
  rotationGracePeriod?: pulumi.Input<string | undefined>;
  /**
   * The token value to be used in API calls
   */
  token?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Token resource.
 */
export interface TokenArgs {
  /**
   * The capabilities available to the token for each dataset
   */
  datasetCapabilities?: pulumi.Input<
    { [key: string]: pulumi.Input<inputs.TokenDatasetCapabilities> } | undefined
  >;
  /**
   * The description of the token
   */
  description?: pulumi.Input<string | undefined>;
  /**
   * The time when the token expires. If not set, the token will not expire. Must be in RFC3339 format
   */
  expiresAt?: pulumi.Input<string | undefined>;
  /**
   * The name of the token
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * The organisation capabilities available to the token
   */
  orgCapabilities?: pulumi.Input<inputs.TokenOrgCapabilities | undefined>;
  /**
   * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
   * How long the previous token remains valid when this token is regenerated during an update (for example: 30s, 5m, 1h). Defaults to 48h when omitted.
   */
  rotationGracePeriod?: pulumi.Input<string | undefined>;
}
