// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class VirtualField extends pulumi.CustomResource {
  /**
   * Get an existing VirtualField resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: VirtualFieldState,
    opts?: pulumi.CustomResourceOptions,
  ): VirtualField {
    return new VirtualField(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'axiom:index/virtualField:VirtualField';

  /**
   * Returns true if the given object is an instance of VirtualField.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is VirtualField {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === VirtualField.__pulumiType;
  }

  /**
   * Dataset the virtual field belongs to
   */
  declare public readonly dataset: pulumi.Output<string>;
  /**
   * Optional description of the virtual field
   */
  declare public readonly description: pulumi.Output<string | undefined>;
  /**
   * Expression defining the virtual field logic
   */
  declare public readonly expression: pulumi.Output<string>;
  /**
   * Name of the virtual field
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * Type of the virtual field
   */
  declare public readonly type: pulumi.Output<string>;
  /**
   * Unit of the virtual field
   */
  declare public readonly unit: pulumi.Output<string>;

  /**
   * Create a VirtualField resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: VirtualFieldArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: VirtualFieldArgs | VirtualFieldState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as VirtualFieldState | undefined;
      resourceInputs['dataset'] = state?.dataset;
      resourceInputs['description'] = state?.description;
      resourceInputs['expression'] = state?.expression;
      resourceInputs['name'] = state?.name;
      resourceInputs['type'] = state?.type;
      resourceInputs['unit'] = state?.unit;
    } else {
      const args = argsOrState as VirtualFieldArgs | undefined;
      if (args?.dataset === undefined && !opts.urn) {
        throw new Error("Missing required property 'dataset'");
      }
      if (args?.expression === undefined && !opts.urn) {
        throw new Error("Missing required property 'expression'");
      }
      resourceInputs['dataset'] = args?.dataset;
      resourceInputs['description'] = args?.description;
      resourceInputs['expression'] = args?.expression;
      resourceInputs['name'] = args?.name;
      resourceInputs['type'] = args?.type;
      resourceInputs['unit'] = args?.unit;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      VirtualField.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering VirtualField resources.
 */
export interface VirtualFieldState {
  /**
   * Dataset the virtual field belongs to
   */
  dataset?: pulumi.Input<string | undefined>;
  /**
   * Optional description of the virtual field
   */
  description?: pulumi.Input<string | undefined>;
  /**
   * Expression defining the virtual field logic
   */
  expression?: pulumi.Input<string | undefined>;
  /**
   * Name of the virtual field
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * Type of the virtual field
   */
  type?: pulumi.Input<string | undefined>;
  /**
   * Unit of the virtual field
   */
  unit?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VirtualField resource.
 */
export interface VirtualFieldArgs {
  /**
   * Dataset the virtual field belongs to
   */
  dataset: pulumi.Input<string>;
  /**
   * Optional description of the virtual field
   */
  description?: pulumi.Input<string | undefined>;
  /**
   * Expression defining the virtual field logic
   */
  expression: pulumi.Input<string>;
  /**
   * Name of the virtual field
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * Type of the virtual field
   */
  type?: pulumi.Input<string | undefined>;
  /**
   * Unit of the virtual field
   */
  unit?: pulumi.Input<string | undefined>;
}
