config:
  vers-infra:zoneName: versidle.com
  vers-infra:appHostname: vers-app-web.fly.dev
  vers-infra:zoneId: fc9e4cdc2fff4aee760c7fd1e71ffe27
encryptionsalt: v1:X3B5c2FRqiA=:v1:6xmc+OObdCNfxT/j:hcfedYdoJcanVVXYfwNGrBvsmAtmLQ==
