config:
  github:owner: zgeoff
  vers-infra:zoneName: versidle.com
  vers-infra:appHostname: vers-app-web.fly.dev
  vers-infra:zoneId: fc9e4cdc2fff4aee760c7fd1e71ffe27
  vers-infra:serviceAuthPublicKey:
    secure: v1:9fX6e9Du2R3qZ/WM:XjVN+MrRFi0sVtI0dvWG0N8ZtFL9HkoYyu53yLBqe+MXTmNgxBH9ietOJUaSlsLtdw+ANl87btRSkTxRvUx9LhYzW/y8qAoB8L9n5hyPo9aPzaYZmGzSs4e8RqSQO1tnN6uPsGoj0CymhGTEHdsS/DKtcN9piL20mtEnjrVLdpQ=
  vers-infra:serviceAuthJWKS:
    secure: v1:VngqA6nB0nihAFSc:oHV45aRlZPHWeutyCnGy3MLRN0MwxHZxiJQi+ReUs9kaGCnQ+ArvmOGtErnXnnGsYJG2YOKLDJGBlGoY5btkK8BEhkvQIMjlaVUxTdWFjgWDLxAjSv7qwGMwEfTR/X6z1/mhtuu4MNsTTimC9/37JxAC2dR5XRk3Qn5971SahhmI9mfXKjq2mDAC+YIAB3SCtCGzeZlUSnSTwu+uz0KHeRkwCgGTvYs8PmTG7bCZ0Lt72es/9NX3hzOgUctukoO06ufb7FxETHdHOGgSF/ffGDG6xNyWyuuVcxIRsI0JGIp4E7X9iQoNW4Sz9zGekly3foBkKBMNvsXoxlbL2D/PgL/U2/RAR6fgFCse5jKadW0lpPkmHPMs6u2JYzLJjoOBN6DZHyevIidx3sdNVzeZnW8HPciFZt5CNhd1dxQfEwESSfmb8Rx07Fvn
encryptionsalt: v1:X3B5c2FRqiA=:v1:6xmc+OObdCNfxT/j:hcfedYdoJcanVVXYfwNGrBvsmAtmLQ==
