app = 'vers-service-verification'
primary_region = 'syd'

[build]

[env]
NODE_ENV = "production"
LOGGING = "info"
HOSTNAME = "fly-local-6pn"
PORT = "3004"
API_IDENTIFIER = "https://api.versidle.com/"

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
