// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class Branch extends pulumi.CustomResource {
  /**
   * Get an existing Branch resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: BranchState,
    opts?: pulumi.CustomResourceOptions,
  ): Branch {
    return new Branch(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/branch:Branch';

  /**
   * Returns true if the given object is an instance of Branch.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Branch {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === Branch.__pulumiType;
  }

  /**
   * Branch logical size in MB.
   */
  declare public readonly /*out*/ logicalSize: pulumi.Output<number>;
  /**
   * Branch name.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * ID of the branch to check out.
   */
  declare public readonly parentId: pulumi.Output<string>;
  /**
   * Log Sequence Number (LSN) horizon for the data to be present in the new branch.
   * See details: https://neon.tech/docs/reference/glossary/#lsn
   */
  declare public readonly parentLsn: pulumi.Output<string>;
  /**
   * Timestamp horizon for the data to be present in the new branch.
   * **Note**: it's defined as Unix epoch.'
   */
  declare public readonly parentTimestamp: pulumi.Output<number>;
  /**
   * Project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;
  /**
   * Set to 'yes' to activate, 'no' to deactivate explicitly, and omit to keep the default value.
   * Set whether the branch is protected.
   */
  declare public readonly protected: pulumi.Output<string | undefined>;

  /**
   * Create a Branch resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: BranchArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: BranchArgs | BranchState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as BranchState | undefined;
      resourceInputs['logicalSize'] = state?.logicalSize;
      resourceInputs['name'] = state?.name;
      resourceInputs['parentId'] = state?.parentId;
      resourceInputs['parentLsn'] = state?.parentLsn;
      resourceInputs['parentTimestamp'] = state?.parentTimestamp;
      resourceInputs['projectId'] = state?.projectId;
      resourceInputs['protected'] = state?.protected;
    } else {
      const args = argsOrState as BranchArgs | undefined;
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      resourceInputs['name'] = args?.name;
      resourceInputs['parentId'] = args?.parentId;
      resourceInputs['parentLsn'] = args?.parentLsn;
      resourceInputs['parentTimestamp'] = args?.parentTimestamp;
      resourceInputs['projectId'] = args?.projectId;
      resourceInputs['protected'] = args?.protected;
      resourceInputs['logicalSize'] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Branch.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Branch resources.
 */
export interface BranchState {
  /**
   * Branch logical size in MB.
   */
  logicalSize?: pulumi.Input<number | undefined>;
  /**
   * Branch name.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * ID of the branch to check out.
   */
  parentId?: pulumi.Input<string | undefined>;
  /**
   * Log Sequence Number (LSN) horizon for the data to be present in the new branch.
   * See details: https://neon.tech/docs/reference/glossary/#lsn
   */
  parentLsn?: pulumi.Input<string | undefined>;
  /**
   * Timestamp horizon for the data to be present in the new branch.
   * **Note**: it's defined as Unix epoch.'
   */
  parentTimestamp?: pulumi.Input<number | undefined>;
  /**
   * Project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
  /**
   * Set to 'yes' to activate, 'no' to deactivate explicitly, and omit to keep the default value.
   * Set whether the branch is protected.
   */
  protected?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Branch resource.
 */
export interface BranchArgs {
  /**
   * Branch name.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * ID of the branch to check out.
   */
  parentId?: pulumi.Input<string | undefined>;
  /**
   * Log Sequence Number (LSN) horizon for the data to be present in the new branch.
   * See details: https://neon.tech/docs/reference/glossary/#lsn
   */
  parentLsn?: pulumi.Input<string | undefined>;
  /**
   * Timestamp horizon for the data to be present in the new branch.
   * **Note**: it's defined as Unix epoch.'
   */
  parentTimestamp?: pulumi.Input<number | undefined>;
  /**
   * Project ID.
   */
  projectId: pulumi.Input<string>;
  /**
   * Set to 'yes' to activate, 'no' to deactivate explicitly, and omit to keep the default value.
   * Set whether the branch is protected.
   */
  protected?: pulumi.Input<string | undefined>;
}
