// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class Database extends pulumi.CustomResource {
  /**
   * Get an existing Database resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: DatabaseState,
    opts?: pulumi.CustomResourceOptions,
  ): Database {
    return new Database(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/database:Database';

  /**
   * Returns true if the given object is an instance of Database.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Database {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === Database.__pulumiType;
  }

  /**
   * Branch ID.
   */
  declare public readonly branchId: pulumi.Output<string>;
  declare public readonly databaseId: pulumi.Output<string>;
  /**
   * Database name.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * Role name of the database owner.
   */
  declare public readonly ownerName: pulumi.Output<string>;
  /**
   * Project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;

  /**
   * Create a Database resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: DatabaseArgs | DatabaseState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as DatabaseState | undefined;
      resourceInputs['branchId'] = state?.branchId;
      resourceInputs['databaseId'] = state?.databaseId;
      resourceInputs['name'] = state?.name;
      resourceInputs['ownerName'] = state?.ownerName;
      resourceInputs['projectId'] = state?.projectId;
    } else {
      const args = argsOrState as DatabaseArgs | undefined;
      if (args?.branchId === undefined && !opts.urn) {
        throw new Error("Missing required property 'branchId'");
      }
      if (args?.ownerName === undefined && !opts.urn) {
        throw new Error("Missing required property 'ownerName'");
      }
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      resourceInputs['branchId'] = args?.branchId;
      resourceInputs['databaseId'] = args?.databaseId;
      resourceInputs['name'] = args?.name;
      resourceInputs['ownerName'] = args?.ownerName;
      resourceInputs['projectId'] = args?.projectId;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Database.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Database resources.
 */
export interface DatabaseState {
  /**
   * Branch ID.
   */
  branchId?: pulumi.Input<string | undefined>;
  databaseId?: pulumi.Input<string | undefined>;
  /**
   * Database name.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * Role name of the database owner.
   */
  ownerName?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
  /**
   * Branch ID.
   */
  branchId: pulumi.Input<string>;
  databaseId?: pulumi.Input<string | undefined>;
  /**
   * Database name.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * Role name of the database owner.
   */
  ownerName: pulumi.Input<string>;
  /**
   * Project ID.
   */
  projectId: pulumi.Input<string>;
}
