// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class Endpoint extends pulumi.CustomResource {
  /**
   * Get an existing Endpoint resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: EndpointState,
    opts?: pulumi.CustomResourceOptions,
  ): Endpoint {
    return new Endpoint(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/endpoint:Endpoint';

  /**
   * Returns true if the given object is an instance of Endpoint.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Endpoint {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === Endpoint.__pulumiType;
  }

  declare public readonly autoscalingLimitMaxCu: pulumi.Output<number>;
  declare public readonly autoscalingLimitMinCu: pulumi.Output<number>;
  /**
   * Branch ID.
   */
  declare public readonly branchId: pulumi.Output<string>;
  /**
   * Provisioner The Neon compute provisioner.
   * Specify the k8s-neonvm provisioner to create a compute endpoint that supports Autoscaling.
   */
  declare public readonly computeProvisioner: pulumi.Output<string>;
  /**
   * Disable the endpoint.
   */
  declare public readonly disabled: pulumi.Output<boolean>;
  /**
   * Endpoint URI.
   */
  declare public readonly /*out*/ host: pulumi.Output<string>;
  declare public readonly pgSettings: pulumi.Output<{ [key: string]: string } | undefined>;
  /**
   * Activate connection pooling.
   * See details: https://neon.tech/docs/connect/connection-pooling
   */
  declare public readonly poolerEnabled: pulumi.Output<boolean>;
  /**
   * Mode of connections pooling.
   * See details: https://neon.tech/docs/connect/connection-pooling
   */
  declare public readonly poolerMode: pulumi.Output<string>;
  /**
   * Project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;
  declare public readonly /*out*/ proxyHost: pulumi.Output<string>;
  /**
   * Deployment region: https://neon.tech/docs/introduction/regions
   */
  declare public readonly regionId: pulumi.Output<string>;
  /**
   * Duration of inactivity in seconds after which the compute endpoint is automatically suspended.
   * The value 0 means use the global default.
   * The value -1 means never suspend. The default value is 300 seconds (5 minutes).
   * The maximum value is 604800 seconds (1 week)
   */
  declare public readonly suspendTimeoutSeconds: pulumi.Output<number>;
  /**
   * Access type. **Note** that a single branch can have only one <span pulumi-lang-nodejs=""readWrite"" pulumi-lang-dotnet=""ReadWrite"" pulumi-lang-go=""readWrite"" pulumi-lang-python=""read_write"" pulumi-lang-yaml=""readWrite"" pulumi-lang-java=""readWrite"" pulumi-lang-hcl=""read_write"">"readWrite"</span> endpoint.
   */
  declare public readonly type: pulumi.Output<string | undefined>;

  /**
   * Create a Endpoint resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: EndpointArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: EndpointArgs | EndpointState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as EndpointState | undefined;
      resourceInputs['autoscalingLimitMaxCu'] = state?.autoscalingLimitMaxCu;
      resourceInputs['autoscalingLimitMinCu'] = state?.autoscalingLimitMinCu;
      resourceInputs['branchId'] = state?.branchId;
      resourceInputs['computeProvisioner'] = state?.computeProvisioner;
      resourceInputs['disabled'] = state?.disabled;
      resourceInputs['host'] = state?.host;
      resourceInputs['pgSettings'] = state?.pgSettings;
      resourceInputs['poolerEnabled'] = state?.poolerEnabled;
      resourceInputs['poolerMode'] = state?.poolerMode;
      resourceInputs['projectId'] = state?.projectId;
      resourceInputs['proxyHost'] = state?.proxyHost;
      resourceInputs['regionId'] = state?.regionId;
      resourceInputs['suspendTimeoutSeconds'] = state?.suspendTimeoutSeconds;
      resourceInputs['type'] = state?.type;
    } else {
      const args = argsOrState as EndpointArgs | undefined;
      if (args?.branchId === undefined && !opts.urn) {
        throw new Error("Missing required property 'branchId'");
      }
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      resourceInputs['autoscalingLimitMaxCu'] = args?.autoscalingLimitMaxCu;
      resourceInputs['autoscalingLimitMinCu'] = args?.autoscalingLimitMinCu;
      resourceInputs['branchId'] = args?.branchId;
      resourceInputs['computeProvisioner'] = args?.computeProvisioner;
      resourceInputs['disabled'] = args?.disabled;
      resourceInputs['pgSettings'] = args?.pgSettings;
      resourceInputs['poolerEnabled'] = args?.poolerEnabled;
      resourceInputs['poolerMode'] = args?.poolerMode;
      resourceInputs['projectId'] = args?.projectId;
      resourceInputs['regionId'] = args?.regionId;
      resourceInputs['suspendTimeoutSeconds'] = args?.suspendTimeoutSeconds;
      resourceInputs['type'] = args?.type;
      resourceInputs['host'] = undefined /*out*/;
      resourceInputs['proxyHost'] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      Endpoint.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Endpoint resources.
 */
export interface EndpointState {
  autoscalingLimitMaxCu?: pulumi.Input<number | undefined>;
  autoscalingLimitMinCu?: pulumi.Input<number | undefined>;
  /**
   * Branch ID.
   */
  branchId?: pulumi.Input<string | undefined>;
  /**
   * Provisioner The Neon compute provisioner.
   * Specify the k8s-neonvm provisioner to create a compute endpoint that supports Autoscaling.
   */
  computeProvisioner?: pulumi.Input<string | undefined>;
  /**
   * Disable the endpoint.
   */
  disabled?: pulumi.Input<boolean | undefined>;
  /**
   * Endpoint URI.
   */
  host?: pulumi.Input<string | undefined>;
  pgSettings?: pulumi.Input<{ [key: string]: pulumi.Input<string> } | undefined>;
  /**
   * Activate connection pooling.
   * See details: https://neon.tech/docs/connect/connection-pooling
   */
  poolerEnabled?: pulumi.Input<boolean | undefined>;
  /**
   * Mode of connections pooling.
   * See details: https://neon.tech/docs/connect/connection-pooling
   */
  poolerMode?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
  proxyHost?: pulumi.Input<string | undefined>;
  /**
   * Deployment region: https://neon.tech/docs/introduction/regions
   */
  regionId?: pulumi.Input<string | undefined>;
  /**
   * Duration of inactivity in seconds after which the compute endpoint is automatically suspended.
   * The value 0 means use the global default.
   * The value -1 means never suspend. The default value is 300 seconds (5 minutes).
   * The maximum value is 604800 seconds (1 week)
   */
  suspendTimeoutSeconds?: pulumi.Input<number | undefined>;
  /**
   * Access type. **Note** that a single branch can have only one <span pulumi-lang-nodejs=""readWrite"" pulumi-lang-dotnet=""ReadWrite"" pulumi-lang-go=""readWrite"" pulumi-lang-python=""read_write"" pulumi-lang-yaml=""readWrite"" pulumi-lang-java=""readWrite"" pulumi-lang-hcl=""read_write"">"readWrite"</span> endpoint.
   */
  type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Endpoint resource.
 */
export interface EndpointArgs {
  autoscalingLimitMaxCu?: pulumi.Input<number | undefined>;
  autoscalingLimitMinCu?: pulumi.Input<number | undefined>;
  /**
   * Branch ID.
   */
  branchId: pulumi.Input<string>;
  /**
   * Provisioner The Neon compute provisioner.
   * Specify the k8s-neonvm provisioner to create a compute endpoint that supports Autoscaling.
   */
  computeProvisioner?: pulumi.Input<string | undefined>;
  /**
   * Disable the endpoint.
   */
  disabled?: pulumi.Input<boolean | undefined>;
  pgSettings?: pulumi.Input<{ [key: string]: pulumi.Input<string> } | undefined>;
  /**
   * Activate connection pooling.
   * See details: https://neon.tech/docs/connect/connection-pooling
   */
  poolerEnabled?: pulumi.Input<boolean | undefined>;
  /**
   * Mode of connections pooling.
   * See details: https://neon.tech/docs/connect/connection-pooling
   */
  poolerMode?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId: pulumi.Input<string>;
  /**
   * Deployment region: https://neon.tech/docs/introduction/regions
   */
  regionId?: pulumi.Input<string | undefined>;
  /**
   * Duration of inactivity in seconds after which the compute endpoint is automatically suspended.
   * The value 0 means use the global default.
   * The value -1 means never suspend. The default value is 300 seconds (5 minutes).
   * The maximum value is 604800 seconds (1 week)
   */
  suspendTimeoutSeconds?: pulumi.Input<number | undefined>;
  /**
   * Access type. **Note** that a single branch can have only one <span pulumi-lang-nodejs=""readWrite"" pulumi-lang-dotnet=""ReadWrite"" pulumi-lang-go=""readWrite"" pulumi-lang-python=""read_write"" pulumi-lang-yaml=""readWrite"" pulumi-lang-java=""readWrite"" pulumi-lang-hcl=""read_write"">"readWrite"</span> endpoint.
   */
  type?: pulumi.Input<string | undefined>;
}
