// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from './types/input';
import * as outputs from './types/output';
import * as utilities from './utilities';

export function getBranchEndpoints(
  args: GetBranchEndpointsArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchEndpointsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'neon:index/getBranchEndpoints:getBranchEndpoints',
    {
      branchId: args.branchId,
      endpoints: args.endpoints,
      id: args.id,
      projectId: args.projectId,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchEndpoints.
 */
export interface GetBranchEndpointsArgs {
  branchId: string;
  endpoints?: inputs.GetBranchEndpointsEndpoint[];
  id?: string;
  projectId: string;
}

/**
 * A collection of values returned by getBranchEndpoints.
 */
export interface GetBranchEndpointsResult {
  readonly branchId: string;
  readonly endpoints?: outputs.GetBranchEndpointsEndpoint[];
  readonly id: string;
  readonly projectId: string;
}
export function getBranchEndpointsOutput(
  args: GetBranchEndpointsOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchEndpointsResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'neon:index/getBranchEndpoints:getBranchEndpoints',
    {
      branchId: args.branchId,
      endpoints: args.endpoints,
      id: args.id,
      projectId: args.projectId,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchEndpoints.
 */
export interface GetBranchEndpointsOutputArgs {
  branchId: pulumi.Input<string>;
  endpoints?: pulumi.Input<pulumi.Input<inputs.GetBranchEndpointsEndpointArgs>[] | undefined>;
  id?: pulumi.Input<string | undefined>;
  projectId: pulumi.Input<string>;
}
