// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from './types/input';
import * as outputs from './types/output';
import * as utilities from './utilities';

export function getBranchRoles(
  args: GetBranchRolesArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchRolesResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'neon:index/getBranchRoles:getBranchRoles',
    {
      branchId: args.branchId,
      id: args.id,
      projectId: args.projectId,
      roles: args.roles,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchRoles.
 */
export interface GetBranchRolesArgs {
  branchId: string;
  id?: string;
  projectId: string;
  roles?: inputs.GetBranchRolesRole[];
}

/**
 * A collection of values returned by getBranchRoles.
 */
export interface GetBranchRolesResult {
  readonly branchId: string;
  readonly id: string;
  readonly projectId: string;
  readonly roles?: outputs.GetBranchRolesRole[];
}
export function getBranchRolesOutput(
  args: GetBranchRolesOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchRolesResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'neon:index/getBranchRoles:getBranchRoles',
    {
      branchId: args.branchId,
      id: args.id,
      projectId: args.projectId,
      roles: args.roles,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchRoles.
 */
export interface GetBranchRolesOutputArgs {
  branchId: pulumi.Input<string>;
  id?: pulumi.Input<string | undefined>;
  projectId: pulumi.Input<string>;
  roles?: pulumi.Input<pulumi.Input<inputs.GetBranchRolesRoleArgs>[] | undefined>;
}
