// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export function getBranchRolePassword(
  args: GetBranchRolePasswordArgs,
  opts?: pulumi.InvokeOptions,
): Promise<GetBranchRolePasswordResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invoke(
    'neon:index/getBranchRolePassword:getBranchRolePassword',
    {
      branchId: args.branchId,
      id: args.id,
      projectId: args.projectId,
      roleName: args.roleName,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchRolePassword.
 */
export interface GetBranchRolePasswordArgs {
  branchId: string;
  id?: string;
  projectId: string;
  roleName: string;
}

/**
 * A collection of values returned by getBranchRolePassword.
 */
export interface GetBranchRolePasswordResult {
  readonly branchId: string;
  readonly id: string;
  readonly password: string;
  readonly projectId: string;
  readonly roleName: string;
}
export function getBranchRolePasswordOutput(
  args: GetBranchRolePasswordOutputArgs,
  opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetBranchRolePasswordResult> {
  opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
  return pulumi.runtime.invokeOutput(
    'neon:index/getBranchRolePassword:getBranchRolePassword',
    {
      branchId: args.branchId,
      id: args.id,
      projectId: args.projectId,
      roleName: args.roleName,
    },
    opts,
    utilities.getPackage(),
  );
}

/**
 * A collection of arguments for invoking getBranchRolePassword.
 */
export interface GetBranchRolePasswordOutputArgs {
  branchId: pulumi.Input<string>;
  id?: pulumi.Input<string | undefined>;
  projectId: pulumi.Input<string>;
  roleName: pulumi.Input<string>;
}
