// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

// Export members:
export { ApiKeyArgs, ApiKeyState } from './apiKey';
export type ApiKey = import('./apiKey').ApiKey;
export const ApiKey: typeof import('./apiKey').ApiKey = null as any;
utilities.lazyLoad(exports, ['ApiKey'], () => require('./apiKey'));

export { BranchArgs, BranchState } from './branch';
export type Branch = import('./branch').Branch;
export const Branch: typeof import('./branch').Branch = null as any;
utilities.lazyLoad(exports, ['Branch'], () => require('./branch'));

export { DatabaseArgs, DatabaseState } from './database';
export type Database = import('./database').Database;
export const Database: typeof import('./database').Database = null as any;
utilities.lazyLoad(exports, ['Database'], () => require('./database'));

export { EndpointArgs, EndpointState } from './endpoint';
export type Endpoint = import('./endpoint').Endpoint;
export const Endpoint: typeof import('./endpoint').Endpoint = null as any;
utilities.lazyLoad(exports, ['Endpoint'], () => require('./endpoint'));

export {
  GetBranchEndpointsArgs,
  GetBranchEndpointsResult,
  GetBranchEndpointsOutputArgs,
} from './getBranchEndpoints';
export const getBranchEndpoints: typeof import('./getBranchEndpoints').getBranchEndpoints =
  null as any;
export const getBranchEndpointsOutput: typeof import('./getBranchEndpoints').getBranchEndpointsOutput =
  null as any;
utilities.lazyLoad(exports, ['getBranchEndpoints', 'getBranchEndpointsOutput'], () =>
  require('./getBranchEndpoints'),
);

export {
  GetBranchRolePasswordArgs,
  GetBranchRolePasswordResult,
  GetBranchRolePasswordOutputArgs,
} from './getBranchRolePassword';
export const getBranchRolePassword: typeof import('./getBranchRolePassword').getBranchRolePassword =
  null as any;
export const getBranchRolePasswordOutput: typeof import('./getBranchRolePassword').getBranchRolePasswordOutput =
  null as any;
utilities.lazyLoad(exports, ['getBranchRolePassword', 'getBranchRolePasswordOutput'], () =>
  require('./getBranchRolePassword'),
);

export {
  GetBranchRolesArgs,
  GetBranchRolesResult,
  GetBranchRolesOutputArgs,
} from './getBranchRoles';
export const getBranchRoles: typeof import('./getBranchRoles').getBranchRoles = null as any;
export const getBranchRolesOutput: typeof import('./getBranchRoles').getBranchRolesOutput =
  null as any;
utilities.lazyLoad(exports, ['getBranchRoles', 'getBranchRolesOutput'], () =>
  require('./getBranchRoles'),
);

export { GetBranchesArgs, GetBranchesResult, GetBranchesOutputArgs } from './getBranches';
export const getBranches: typeof import('./getBranches').getBranches = null as any;
export const getBranchesOutput: typeof import('./getBranches').getBranchesOutput = null as any;
utilities.lazyLoad(exports, ['getBranches', 'getBranchesOutput'], () => require('./getBranches'));

export { GetProjectArgs, GetProjectResult, GetProjectOutputArgs } from './getProject';
export const getProject: typeof import('./getProject').getProject = null as any;
export const getProjectOutput: typeof import('./getProject').getProjectOutput = null as any;
utilities.lazyLoad(exports, ['getProject', 'getProjectOutput'], () => require('./getProject'));

export { JwksUrlArgs, JwksUrlState } from './jwksUrl';
export type JwksUrl = import('./jwksUrl').JwksUrl;
export const JwksUrl: typeof import('./jwksUrl').JwksUrl = null as any;
utilities.lazyLoad(exports, ['JwksUrl'], () => require('./jwksUrl'));

export { OrgApiKeyArgs, OrgApiKeyState } from './orgApiKey';
export type OrgApiKey = import('./orgApiKey').OrgApiKey;
export const OrgApiKey: typeof import('./orgApiKey').OrgApiKey = null as any;
utilities.lazyLoad(exports, ['OrgApiKey'], () => require('./orgApiKey'));

export { ProjectArgs, ProjectState } from './project';
export type Project = import('./project').Project;
export const Project: typeof import('./project').Project = null as any;
utilities.lazyLoad(exports, ['Project'], () => require('./project'));

export { ProjectPermissionArgs, ProjectPermissionState } from './projectPermission';
export type ProjectPermission = import('./projectPermission').ProjectPermission;
export const ProjectPermission: typeof import('./projectPermission').ProjectPermission =
  null as any;
utilities.lazyLoad(exports, ['ProjectPermission'], () => require('./projectPermission'));

export * from './provider';
import { Provider } from './provider';

export { RoleArgs, RoleState } from './role';
export type Role = import('./role').Role;
export const Role: typeof import('./role').Role = null as any;
utilities.lazyLoad(exports, ['Role'], () => require('./role'));

export { VpcEndpointAssignmentArgs, VpcEndpointAssignmentState } from './vpcEndpointAssignment';
export type VpcEndpointAssignment = import('./vpcEndpointAssignment').VpcEndpointAssignment;
export const VpcEndpointAssignment: typeof import('./vpcEndpointAssignment').VpcEndpointAssignment =
  null as any;
utilities.lazyLoad(exports, ['VpcEndpointAssignment'], () => require('./vpcEndpointAssignment'));

export { VpcEndpointRestrictionArgs, VpcEndpointRestrictionState } from './vpcEndpointRestriction';
export type VpcEndpointRestriction = import('./vpcEndpointRestriction').VpcEndpointRestriction;
export const VpcEndpointRestriction: typeof import('./vpcEndpointRestriction').VpcEndpointRestriction =
  null as any;
utilities.lazyLoad(exports, ['VpcEndpointRestriction'], () => require('./vpcEndpointRestriction'));

// Export sub-modules:
import * as config from './config';
import * as types from './types';

export { config, types };

const _module = {
  version: utilities.getVersion(),
  construct: (name: string, type: string, urn: string): pulumi.Resource => {
    switch (type) {
      case 'neon:index/apiKey:ApiKey':
        return new ApiKey(name, <any>undefined, { urn });
      case 'neon:index/branch:Branch':
        return new Branch(name, <any>undefined, { urn });
      case 'neon:index/database:Database':
        return new Database(name, <any>undefined, { urn });
      case 'neon:index/endpoint:Endpoint':
        return new Endpoint(name, <any>undefined, { urn });
      case 'neon:index/jwksUrl:JwksUrl':
        return new JwksUrl(name, <any>undefined, { urn });
      case 'neon:index/orgApiKey:OrgApiKey':
        return new OrgApiKey(name, <any>undefined, { urn });
      case 'neon:index/project:Project':
        return new Project(name, <any>undefined, { urn });
      case 'neon:index/projectPermission:ProjectPermission':
        return new ProjectPermission(name, <any>undefined, { urn });
      case 'neon:index/role:Role':
        return new Role(name, <any>undefined, { urn });
      case 'neon:index/vpcEndpointAssignment:VpcEndpointAssignment':
        return new VpcEndpointAssignment(name, <any>undefined, { urn });
      case 'neon:index/vpcEndpointRestriction:VpcEndpointRestriction':
        return new VpcEndpointRestriction(name, <any>undefined, { urn });
      default:
        throw new Error(`unknown resource type ${type}`);
    }
  },
};
pulumi.runtime.registerResourceModule('neon', 'index/apiKey', _module);
pulumi.runtime.registerResourceModule('neon', 'index/branch', _module);
pulumi.runtime.registerResourceModule('neon', 'index/database', _module);
pulumi.runtime.registerResourceModule('neon', 'index/endpoint', _module);
pulumi.runtime.registerResourceModule('neon', 'index/jwksUrl', _module);
pulumi.runtime.registerResourceModule('neon', 'index/orgApiKey', _module);
pulumi.runtime.registerResourceModule('neon', 'index/project', _module);
pulumi.runtime.registerResourceModule('neon', 'index/projectPermission', _module);
pulumi.runtime.registerResourceModule('neon', 'index/role', _module);
pulumi.runtime.registerResourceModule('neon', 'index/vpcEndpointAssignment', _module);
pulumi.runtime.registerResourceModule('neon', 'index/vpcEndpointRestriction', _module);
pulumi.runtime.registerResourcePackage('neon', {
  version: utilities.getVersion(),
  constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
    if (type !== 'pulumi:providers:neon') {
      throw new Error(`unknown provider type ${type}`);
    }
    return new Provider(name, <any>undefined, { urn });
  },
});
