// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class JwksUrl extends pulumi.CustomResource {
  /**
   * Get an existing JwksUrl resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: JwksUrlState,
    opts?: pulumi.CustomResourceOptions,
  ): JwksUrl {
    return new JwksUrl(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/jwksUrl:JwksUrl';

  /**
   * Returns true if the given object is an instance of JwksUrl.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is JwksUrl {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === JwksUrl.__pulumiType;
  }

  /**
   * Branch ID.
   */
  declare public readonly branchId: pulumi.Output<string | undefined>;
  /**
   * The URL that lists the JWKS.
   */
  declare public readonly jwksUrl: pulumi.Output<string>;
  declare public readonly jwksUrlId: pulumi.Output<string>;
  /**
   * The name of the required JWT Audience to be used.
   */
  declare public readonly jwtAudience: pulumi.Output<string | undefined>;
  /**
   * Project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;
  /**
   * The name of the authentication provider.
   */
  declare public readonly providerName: pulumi.Output<string>;
  /**
   * The roles the JWKS should be mapped to.
   */
  declare public readonly roleNames: pulumi.Output<string[]>;

  /**
   * Create a JwksUrl resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: JwksUrlArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: JwksUrlArgs | JwksUrlState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as JwksUrlState | undefined;
      resourceInputs['branchId'] = state?.branchId;
      resourceInputs['jwksUrl'] = state?.jwksUrl;
      resourceInputs['jwksUrlId'] = state?.jwksUrlId;
      resourceInputs['jwtAudience'] = state?.jwtAudience;
      resourceInputs['projectId'] = state?.projectId;
      resourceInputs['providerName'] = state?.providerName;
      resourceInputs['roleNames'] = state?.roleNames;
    } else {
      const args = argsOrState as JwksUrlArgs | undefined;
      if (args?.jwksUrl === undefined && !opts.urn) {
        throw new Error("Missing required property 'jwksUrl'");
      }
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      if (args?.providerName === undefined && !opts.urn) {
        throw new Error("Missing required property 'providerName'");
      }
      if (args?.roleNames === undefined && !opts.urn) {
        throw new Error("Missing required property 'roleNames'");
      }
      resourceInputs['branchId'] = args?.branchId;
      resourceInputs['jwksUrl'] = args?.jwksUrl;
      resourceInputs['jwksUrlId'] = args?.jwksUrlId;
      resourceInputs['jwtAudience'] = args?.jwtAudience;
      resourceInputs['projectId'] = args?.projectId;
      resourceInputs['providerName'] = args?.providerName;
      resourceInputs['roleNames'] = args?.roleNames;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      JwksUrl.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering JwksUrl resources.
 */
export interface JwksUrlState {
  /**
   * Branch ID.
   */
  branchId?: pulumi.Input<string | undefined>;
  /**
   * The URL that lists the JWKS.
   */
  jwksUrl?: pulumi.Input<string | undefined>;
  jwksUrlId?: pulumi.Input<string | undefined>;
  /**
   * The name of the required JWT Audience to be used.
   */
  jwtAudience?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
  /**
   * The name of the authentication provider.
   */
  providerName?: pulumi.Input<string | undefined>;
  /**
   * The roles the JWKS should be mapped to.
   */
  roleNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a JwksUrl resource.
 */
export interface JwksUrlArgs {
  /**
   * Branch ID.
   */
  branchId?: pulumi.Input<string | undefined>;
  /**
   * The URL that lists the JWKS.
   */
  jwksUrl: pulumi.Input<string>;
  jwksUrlId?: pulumi.Input<string | undefined>;
  /**
   * The name of the required JWT Audience to be used.
   */
  jwtAudience?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId: pulumi.Input<string>;
  /**
   * The name of the authentication provider.
   */
  providerName: pulumi.Input<string>;
  /**
   * The roles the JWKS should be mapped to.
   */
  roleNames: pulumi.Input<pulumi.Input<string>[]>;
}
