// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class OrgApiKey extends pulumi.CustomResource {
  /**
   * Get an existing OrgApiKey resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: OrgApiKeyState,
    opts?: pulumi.CustomResourceOptions,
  ): OrgApiKey {
    return new OrgApiKey(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/orgApiKey:OrgApiKey';

  /**
   * Returns true if the given object is an instance of OrgApiKey.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is OrgApiKey {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === OrgApiKey.__pulumiType;
  }

  /**
   * The generated 64-bit token required to access the Neon API.
   */
  declare public readonly /*out*/ key: pulumi.Output<string>;
  /**
   * The name of the API Key.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * The organisation ID.
   */
  declare public readonly orgId: pulumi.Output<string>;
  /**
   * The project ID to which this key will grant the access to.
   */
  declare public readonly projectId: pulumi.Output<string | undefined>;

  /**
   * Create a OrgApiKey resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: OrgApiKeyArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: OrgApiKeyArgs | OrgApiKeyState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as OrgApiKeyState | undefined;
      resourceInputs['key'] = state?.key;
      resourceInputs['name'] = state?.name;
      resourceInputs['orgId'] = state?.orgId;
      resourceInputs['projectId'] = state?.projectId;
    } else {
      const args = argsOrState as OrgApiKeyArgs | undefined;
      if (args?.orgId === undefined && !opts.urn) {
        throw new Error("Missing required property 'orgId'");
      }
      resourceInputs['name'] = args?.name;
      resourceInputs['orgId'] = args?.orgId;
      resourceInputs['projectId'] = args?.projectId;
      resourceInputs['key'] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ['key'] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      OrgApiKey.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering OrgApiKey resources.
 */
export interface OrgApiKeyState {
  /**
   * The generated 64-bit token required to access the Neon API.
   */
  key?: pulumi.Input<string | undefined>;
  /**
   * The name of the API Key.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * The organisation ID.
   */
  orgId?: pulumi.Input<string | undefined>;
  /**
   * The project ID to which this key will grant the access to.
   */
  projectId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrgApiKey resource.
 */
export interface OrgApiKeyArgs {
  /**
   * The name of the API Key.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * The organisation ID.
   */
  orgId: pulumi.Input<string>;
  /**
   * The project ID to which this key will grant the access to.
   */
  projectId?: pulumi.Input<string | undefined>;
}
