// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class ProjectPermission extends pulumi.CustomResource {
  /**
   * Get an existing ProjectPermission resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: ProjectPermissionState,
    opts?: pulumi.CustomResourceOptions,
  ): ProjectPermission {
    return new ProjectPermission(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/projectPermission:ProjectPermission';

  /**
   * Returns true if the given object is an instance of ProjectPermission.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is ProjectPermission {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === ProjectPermission.__pulumiType;
  }

  /**
   * Email of the user whom to grant project permission.
   */
  declare public readonly grantee: pulumi.Output<string>;
  /**
   * Project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;

  /**
   * Create a ProjectPermission resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: ProjectPermissionArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: ProjectPermissionArgs | ProjectPermissionState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as ProjectPermissionState | undefined;
      resourceInputs['grantee'] = state?.grantee;
      resourceInputs['projectId'] = state?.projectId;
    } else {
      const args = argsOrState as ProjectPermissionArgs | undefined;
      if (args?.grantee === undefined && !opts.urn) {
        throw new Error("Missing required property 'grantee'");
      }
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      resourceInputs['grantee'] = args?.grantee;
      resourceInputs['projectId'] = args?.projectId;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      ProjectPermission.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering ProjectPermission resources.
 */
export interface ProjectPermissionState {
  /**
   * Email of the user whom to grant project permission.
   */
  grantee?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProjectPermission resource.
 */
export interface ProjectPermissionArgs {
  /**
   * Email of the user whom to grant project permission.
   */
  grantee: pulumi.Input<string>;
  /**
   * Project ID.
   */
  projectId: pulumi.Input<string>;
}
