// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class Role extends pulumi.CustomResource {
  /**
   * Get an existing Role resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: RoleState,
    opts?: pulumi.CustomResourceOptions,
  ): Role {
    return new Role(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/role:Role';

  /**
   * Returns true if the given object is an instance of Role.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is Role {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === Role.__pulumiType;
  }

  /**
   * Branch ID.
   */
  declare public readonly branchId: pulumi.Output<string>;
  /**
   * Role name.
   */
  declare public readonly name: pulumi.Output<string>;
  /**
   * Database authentication password.
   */
  declare public readonly /*out*/ password: pulumi.Output<string>;
  /**
   * Project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;
  declare public readonly /*out*/ protected: pulumi.Output<boolean>;
  declare public readonly roleId: pulumi.Output<string>;

  /**
   * Create a Role resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: RoleArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: RoleArgs | RoleState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as RoleState | undefined;
      resourceInputs['branchId'] = state?.branchId;
      resourceInputs['name'] = state?.name;
      resourceInputs['password'] = state?.password;
      resourceInputs['projectId'] = state?.projectId;
      resourceInputs['protected'] = state?.protected;
      resourceInputs['roleId'] = state?.roleId;
    } else {
      const args = argsOrState as RoleArgs | undefined;
      if (args?.branchId === undefined && !opts.urn) {
        throw new Error("Missing required property 'branchId'");
      }
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      resourceInputs['branchId'] = args?.branchId;
      resourceInputs['name'] = args?.name;
      resourceInputs['projectId'] = args?.projectId;
      resourceInputs['roleId'] = args?.roleId;
      resourceInputs['password'] = undefined /*out*/;
      resourceInputs['protected'] = undefined /*out*/;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ['password'] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      Role.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering Role resources.
 */
export interface RoleState {
  /**
   * Branch ID.
   */
  branchId?: pulumi.Input<string | undefined>;
  /**
   * Role name.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * Database authentication password.
   */
  password?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
  protected?: pulumi.Input<boolean | undefined>;
  roleId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Role resource.
 */
export interface RoleArgs {
  /**
   * Branch ID.
   */
  branchId: pulumi.Input<string>;
  /**
   * Role name.
   */
  name?: pulumi.Input<string | undefined>;
  /**
   * Project ID.
   */
  projectId: pulumi.Input<string>;
  roleId?: pulumi.Input<string | undefined>;
}
