// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class VpcEndpointRestriction extends pulumi.CustomResource {
  /**
   * Get an existing VpcEndpointRestriction resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: VpcEndpointRestrictionState,
    opts?: pulumi.CustomResourceOptions,
  ): VpcEndpointRestriction {
    return new VpcEndpointRestriction(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/vpcEndpointRestriction:VpcEndpointRestriction';

  /**
   * Returns true if the given object is an instance of VpcEndpointRestriction.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is VpcEndpointRestriction {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === VpcEndpointRestriction.__pulumiType;
  }

  /**
   * A descriptive label for the VPC endpoint.
   */
  declare public readonly label: pulumi.Output<string>;
  /**
   * The Neon project ID.
   */
  declare public readonly projectId: pulumi.Output<string>;
  /**
   * The VPC endpoint ID.
   */
  declare public readonly vpcEndpointId: pulumi.Output<string>;
  declare public readonly vpcEndpointRestrictionId: pulumi.Output<string>;

  /**
   * Create a VpcEndpointRestriction resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: VpcEndpointRestrictionArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: VpcEndpointRestrictionArgs | VpcEndpointRestrictionState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as VpcEndpointRestrictionState | undefined;
      resourceInputs['label'] = state?.label;
      resourceInputs['projectId'] = state?.projectId;
      resourceInputs['vpcEndpointId'] = state?.vpcEndpointId;
      resourceInputs['vpcEndpointRestrictionId'] = state?.vpcEndpointRestrictionId;
    } else {
      const args = argsOrState as VpcEndpointRestrictionArgs | undefined;
      if (args?.label === undefined && !opts.urn) {
        throw new Error("Missing required property 'label'");
      }
      if (args?.projectId === undefined && !opts.urn) {
        throw new Error("Missing required property 'projectId'");
      }
      if (args?.vpcEndpointId === undefined && !opts.urn) {
        throw new Error("Missing required property 'vpcEndpointId'");
      }
      resourceInputs['label'] = args?.label;
      resourceInputs['projectId'] = args?.projectId;
      resourceInputs['vpcEndpointId'] = args?.vpcEndpointId;
      resourceInputs['vpcEndpointRestrictionId'] = args?.vpcEndpointRestrictionId;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      VpcEndpointRestriction.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering VpcEndpointRestriction resources.
 */
export interface VpcEndpointRestrictionState {
  /**
   * A descriptive label for the VPC endpoint.
   */
  label?: pulumi.Input<string | undefined>;
  /**
   * The Neon project ID.
   */
  projectId?: pulumi.Input<string | undefined>;
  /**
   * The VPC endpoint ID.
   */
  vpcEndpointId?: pulumi.Input<string | undefined>;
  vpcEndpointRestrictionId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VpcEndpointRestriction resource.
 */
export interface VpcEndpointRestrictionArgs {
  /**
   * A descriptive label for the VPC endpoint.
   */
  label: pulumi.Input<string>;
  /**
   * The Neon project ID.
   */
  projectId: pulumi.Input<string>;
  /**
   * The VPC endpoint ID.
   */
  vpcEndpointId: pulumi.Input<string>;
  vpcEndpointRestrictionId?: pulumi.Input<string | undefined>;
}
