// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from './utilities';

export class VpcEndpointAssignment extends pulumi.CustomResource {
  /**
   * Get an existing VpcEndpointAssignment resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: VpcEndpointAssignmentState,
    opts?: pulumi.CustomResourceOptions,
  ): VpcEndpointAssignment {
    return new VpcEndpointAssignment(name, <any>state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = 'neon:index/vpcEndpointAssignment:VpcEndpointAssignment';

  /**
   * Returns true if the given object is an instance of VpcEndpointAssignment.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is VpcEndpointAssignment {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj['__pulumiType'] === VpcEndpointAssignment.__pulumiType;
  }

  /**
   * A descriptive label for the VPC endpoint.
   */
  declare public readonly label: pulumi.Output<string>;
  /**
   * The Neon organization ID.
   */
  declare public readonly orgId: pulumi.Output<string>;
  /**
   * The Neon region ID.
   */
  declare public readonly regionId: pulumi.Output<string>;
  declare public readonly vpcEndpointAssignmentId: pulumi.Output<string>;
  /**
   * The VPC endpoint ID.
   */
  declare public readonly vpcEndpointId: pulumi.Output<string>;

  /**
   * Create a VpcEndpointAssignment resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: VpcEndpointAssignmentArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: VpcEndpointAssignmentArgs | VpcEndpointAssignmentState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as VpcEndpointAssignmentState | undefined;
      resourceInputs['label'] = state?.label;
      resourceInputs['orgId'] = state?.orgId;
      resourceInputs['regionId'] = state?.regionId;
      resourceInputs['vpcEndpointAssignmentId'] = state?.vpcEndpointAssignmentId;
      resourceInputs['vpcEndpointId'] = state?.vpcEndpointId;
    } else {
      const args = argsOrState as VpcEndpointAssignmentArgs | undefined;
      if (args?.label === undefined && !opts.urn) {
        throw new Error("Missing required property 'label'");
      }
      if (args?.orgId === undefined && !opts.urn) {
        throw new Error("Missing required property 'orgId'");
      }
      if (args?.regionId === undefined && !opts.urn) {
        throw new Error("Missing required property 'regionId'");
      }
      if (args?.vpcEndpointId === undefined && !opts.urn) {
        throw new Error("Missing required property 'vpcEndpointId'");
      }
      resourceInputs['label'] = args?.label;
      resourceInputs['orgId'] = args?.orgId;
      resourceInputs['regionId'] = args?.regionId;
      resourceInputs['vpcEndpointAssignmentId'] = args?.vpcEndpointAssignmentId;
      resourceInputs['vpcEndpointId'] = args?.vpcEndpointId;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(
      VpcEndpointAssignment.__pulumiType,
      name,
      resourceInputs,
      opts,
      false /*dependency*/,
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering VpcEndpointAssignment resources.
 */
export interface VpcEndpointAssignmentState {
  /**
   * A descriptive label for the VPC endpoint.
   */
  label?: pulumi.Input<string | undefined>;
  /**
   * The Neon organization ID.
   */
  orgId?: pulumi.Input<string | undefined>;
  /**
   * The Neon region ID.
   */
  regionId?: pulumi.Input<string | undefined>;
  vpcEndpointAssignmentId?: pulumi.Input<string | undefined>;
  /**
   * The VPC endpoint ID.
   */
  vpcEndpointId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VpcEndpointAssignment resource.
 */
export interface VpcEndpointAssignmentArgs {
  /**
   * A descriptive label for the VPC endpoint.
   */
  label: pulumi.Input<string>;
  /**
   * The Neon organization ID.
   */
  orgId: pulumi.Input<string>;
  /**
   * The Neon region ID.
   */
  regionId: pulumi.Input<string>;
  vpcEndpointAssignmentId?: pulumi.Input<string | undefined>;
  /**
   * The VPC endpoint ID.
   */
  vpcEndpointId: pulumi.Input<string>;
}
