// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from '../types/input';
import * as outputs from '../types/output';

export interface NotifierProperties {
  customWebhook?: pulumi.Input<inputs.NotifierPropertiesCustomWebhook | undefined>;
  discord?: pulumi.Input<inputs.NotifierPropertiesDiscord | undefined>;
  discordWebhook?: pulumi.Input<inputs.NotifierPropertiesDiscordWebhook | undefined>;
  email?: pulumi.Input<inputs.NotifierPropertiesEmail | undefined>;
  opsgenie?: pulumi.Input<inputs.NotifierPropertiesOpsgenie | undefined>;
  pagerduty?: pulumi.Input<inputs.NotifierPropertiesPagerduty | undefined>;
  slack?: pulumi.Input<inputs.NotifierPropertiesSlack | undefined>;
  webhook?: pulumi.Input<inputs.NotifierPropertiesWebhook | undefined>;
}

export interface NotifierPropertiesCustomWebhook {
  /**
   * The JSON body
   */
  body: pulumi.Input<string>;
  /**
   * Any headers associated with the request
   */
  headers?: pulumi.Input<{ [key: string]: pulumi.Input<string> } | undefined>;
  /**
   * The webhook URL
   */
  url: pulumi.Input<string>;
}

export interface NotifierPropertiesDiscord {
  /**
   * The discord channel
   */
  discordChannel: pulumi.Input<string>;
  /**
   * The discord token
   */
  discordToken: pulumi.Input<string>;
}

export interface NotifierPropertiesDiscordWebhook {
  /**
   * The discord webhook URL
   */
  discordWebhookUrl: pulumi.Input<string>;
}

export interface NotifierPropertiesEmail {
  /**
   * The emails to be notified
   */
  emails: pulumi.Input<pulumi.Input<string>[]>;
}

export interface NotifierPropertiesOpsgenie {
  /**
   * The opsgenie API key
   */
  apiKey: pulumi.Input<string>;
  /**
   * The opsgenie is EU
   */
  isEu: pulumi.Input<boolean>;
}

export interface NotifierPropertiesPagerduty {
  /**
   * The pagerduty routing key
   */
  routingKey: pulumi.Input<string>;
  /**
   * The pager duty token
   *
   * @deprecated Deprecated
   */
  token?: pulumi.Input<string | undefined>;
}

export interface NotifierPropertiesSlack {
  /**
   * The slack URL
   */
  slackUrl: pulumi.Input<string>;
}

export interface NotifierPropertiesWebhook {
  /**
   * The webhook URL
   */
  url: pulumi.Input<string>;
}

export interface TokenDatasetCapabilities {
  /**
   * Ability to manage the data in a dataset
   */
  datas?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to ingest into the specified dataset
   */
  ingests?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to query the specified dataset
   */
  queries?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to perform actions on starred queries for the specified dataset
   */
  starredQueries?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to trim the data in a dataset
   */
  trims?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to vacuum the fields in a dataset
   */
  vacuums?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to perform actions on virtual fields for the provided dataset
   */
  virtualFields?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface TokenOrgCapabilities {
  /**
   * Ability to perform actions on annotations
   */
  annotations?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage api tokens
   */
  apiTokens?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to read the audit log
   */
  auditLogs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage billing information
   */
  billings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage dashboards
   */
  dashboards?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage datasets
   */
  datasets?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage endpoints
   */
  endpoints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage flows
   */
  flows?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage integrations
   */
  integrations?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage monitors
   */
  monitors?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage notifiers
   */
  notifiers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage roles and groups
   */
  rbacs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage shared access keys
   */
  sharedAccessKeys?: pulumi.Input<pulumi.Input<string>[] | undefined>;
  /**
   * Ability to manage users
   */
  users?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
