// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from '../types/input';
import * as outputs from '../types/output';

export interface GetNotifierProperties {
  customWebhook: outputs.GetNotifierPropertiesCustomWebhook;
  discord: outputs.GetNotifierPropertiesDiscord;
  discordWebhook: outputs.GetNotifierPropertiesDiscordWebhook;
  email: outputs.GetNotifierPropertiesEmail;
  opsgenie: outputs.GetNotifierPropertiesOpsgenie;
  pagerduty: outputs.GetNotifierPropertiesPagerduty;
  slack: outputs.GetNotifierPropertiesSlack;
  webhook: outputs.GetNotifierPropertiesWebhook;
}

export interface GetNotifierPropertiesCustomWebhook {
  /**
   * The JSON body
   */
  body: string;
  /**
   * Any headers associated with the request
   */
  headers: { [key: string]: string };
  /**
   * The webhook URL
   */
  url: string;
}

export interface GetNotifierPropertiesDiscord {
  /**
   * The discord channel
   */
  discordChannel: string;
  /**
   * The discord token
   */
  discordToken: string;
}

export interface GetNotifierPropertiesDiscordWebhook {
  /**
   * The discord webhook URL
   */
  discordWebhookUrl: string;
}

export interface GetNotifierPropertiesEmail {
  /**
   * The emails to be notified
   */
  emails: string[];
}

export interface GetNotifierPropertiesOpsgenie {
  /**
   * The opsgenie API key
   */
  apiKey: string;
  /**
   * The opsgenie is EU
   */
  isEu: boolean;
}

export interface GetNotifierPropertiesPagerduty {
  /**
   * The pagerduty routing key
   */
  routingKey: string;
  /**
   * The pager duty token
   */
  token: string;
}

export interface GetNotifierPropertiesSlack {
  /**
   * The slack URL
   */
  slackUrl: string;
}

export interface GetNotifierPropertiesWebhook {
  /**
   * The webhook URL
   */
  url: string;
}

export interface GetTokenDatasetCapabilities {
  /**
   * Ability to manage the data in a dataset
   */
  datas: string[];
  /**
   * Ability to ingest into the specified dataset
   */
  ingests: string[];
  /**
   * Ability to query the specified dataset
   */
  queries: string[];
  /**
   * Ability to perform actions on starred queries for the specified dataset
   */
  starredQueries: string[];
  /**
   * Ability to trim the data in a dataset
   */
  trims: string[];
  /**
   * Ability to vacuum the fields in a dataset
   */
  vacuums: string[];
  /**
   * Ability to perform actions on virtual fields for the provided dataset
   */
  virtualFields: string[];
}

export interface GetTokenOrgCapabilities {
  /**
   * Ability to perform actions on annotations
   */
  annotations: string[];
  /**
   * Ability to manage api tokens
   */
  apiTokens: string[];
  /**
   * Ability to read the audit log
   */
  auditLogs: string[];
  /**
   * Ability to manage billing information
   */
  billings: string[];
  /**
   * Ability to manage dashboards
   */
  dashboards: string[];
  /**
   * Ability to manage datasets
   */
  datasets: string[];
  /**
   * Ability to manage endpoints
   */
  endpoints: string[];
  /**
   * Ability to manage flows
   */
  flows: string[];
  /**
   * Ability to manage integrations
   */
  integrations: string[];
  /**
   * Ability to manage monitors
   */
  monitors: string[];
  /**
   * Ability to manage notifiers
   */
  notifiers: string[];
  /**
   * Ability to manage roles and groups
   */
  rbacs: string[];
  /**
   * Ability to manage shared access keys
   */
  sharedAccessKeys: string[];
  /**
   * Ability to manage users
   */
  users: string[];
}

export interface NotifierProperties {
  customWebhook?: outputs.NotifierPropertiesCustomWebhook;
  discord?: outputs.NotifierPropertiesDiscord;
  discordWebhook?: outputs.NotifierPropertiesDiscordWebhook;
  email?: outputs.NotifierPropertiesEmail;
  opsgenie?: outputs.NotifierPropertiesOpsgenie;
  pagerduty?: outputs.NotifierPropertiesPagerduty;
  slack?: outputs.NotifierPropertiesSlack;
  webhook?: outputs.NotifierPropertiesWebhook;
}

export interface NotifierPropertiesCustomWebhook {
  /**
   * The JSON body
   */
  body: string;
  /**
   * Any headers associated with the request
   */
  headers?: { [key: string]: string };
  /**
   * The webhook URL
   */
  url: string;
}

export interface NotifierPropertiesDiscord {
  /**
   * The discord channel
   */
  discordChannel: string;
  /**
   * The discord token
   */
  discordToken: string;
}

export interface NotifierPropertiesDiscordWebhook {
  /**
   * The discord webhook URL
   */
  discordWebhookUrl: string;
}

export interface NotifierPropertiesEmail {
  /**
   * The emails to be notified
   */
  emails: string[];
}

export interface NotifierPropertiesOpsgenie {
  /**
   * The opsgenie API key
   */
  apiKey: string;
  /**
   * The opsgenie is EU
   */
  isEu: boolean;
}

export interface NotifierPropertiesPagerduty {
  /**
   * The pagerduty routing key
   */
  routingKey: string;
  /**
   * The pager duty token
   *
   * @deprecated Deprecated
   */
  token?: string;
}

export interface NotifierPropertiesSlack {
  /**
   * The slack URL
   */
  slackUrl: string;
}

export interface NotifierPropertiesWebhook {
  /**
   * The webhook URL
   */
  url: string;
}

export interface TokenDatasetCapabilities {
  /**
   * Ability to manage the data in a dataset
   */
  datas: string[];
  /**
   * Ability to ingest into the specified dataset
   */
  ingests: string[];
  /**
   * Ability to query the specified dataset
   */
  queries: string[];
  /**
   * Ability to perform actions on starred queries for the specified dataset
   */
  starredQueries: string[];
  /**
   * Ability to trim the data in a dataset
   */
  trims: string[];
  /**
   * Ability to vacuum the fields in a dataset
   */
  vacuums: string[];
  /**
   * Ability to perform actions on virtual fields for the provided dataset
   */
  virtualFields: string[];
}

export interface TokenOrgCapabilities {
  /**
   * Ability to perform actions on annotations
   */
  annotations: string[];
  /**
   * Ability to manage api tokens
   */
  apiTokens: string[];
  /**
   * Ability to read the audit log
   */
  auditLogs: string[];
  /**
   * Ability to manage billing information
   */
  billings: string[];
  /**
   * Ability to manage dashboards
   */
  dashboards: string[];
  /**
   * Ability to manage datasets
   */
  datasets: string[];
  /**
   * Ability to manage endpoints
   */
  endpoints: string[];
  /**
   * Ability to manage flows
   */
  flows: string[];
  /**
   * Ability to manage integrations
   */
  integrations: string[];
  /**
   * Ability to manage monitors
   */
  monitors: string[];
  /**
   * Ability to manage notifiers
   */
  notifiers: string[];
  /**
   * Ability to manage roles and groups
   */
  rbacs: string[];
  /**
   * Ability to manage shared access keys
   */
  sharedAccessKeys: string[];
  /**
   * Ability to manage users
   */
  users: string[];
}
