// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from '../utilities';

declare var exports: any;
const __config = new pulumi.Config('neon');

/**
 * API access key. Default is read from the environment variable `NEON_API_KEY`.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, 'apiKey', {
  get() {
    return __config.get('apiKey');
  },
  enumerable: true,
});
