/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AvatarClass = 'brute' | 'scholar' | 'scoundrel';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VerificationType = '2fa' | '2fa-setup' | 'change-email' | 'onboarding';

export interface Avatars {
  class: AvatarClass;
  createdAt: Generated<Timestamp>;
  id: string;
  level: Generated<number>;
  name: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
  xp: Generated<number>;
}

export interface ConsumedTransactionTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  jti: string;
}

export interface PendingTransactions {
  action: string;
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string;
  sessionId: string | null;
  target: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string;
  previousRefreshToken: string | null;
  refreshToken: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
  verified: Generated<boolean>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: string;
  name: string;
  passwordHash: string | null;
  passwordResetToken: string | null;
  passwordResetTokenExpiresAt: Timestamp | null;
  seed: Generated<number>;
  updatedAt: Generated<Timestamp>;
  username: string;
}

export interface Verifications {
  algorithm: string;
  charSet: string;
  createdAt: Generated<Timestamp>;
  digits: number;
  expiresAt: Timestamp | null;
  id: string;
  lastVerifiedAt: Timestamp | null;
  lastVerifiedCode: string | null;
  period: number;
  secret: string;
  target: string;
  type: VerificationType;
}

export interface DB {
  avatars: Avatars;
  consumedTransactionTokens: ConsumedTransactionTokens;
  pendingTransactions: PendingTransactions;
  sessions: Sessions;
  users: Users;
  verifications: Verifications;
}
