// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from '../utilities';

declare var exports: any;
const __config = new pulumi.Config('axiom');

/**
 * The Axiom API token.
 */
export declare const apiToken: string | undefined;
Object.defineProperty(exports, 'apiToken', {
  get() {
    return __config.get('apiToken');
  },
  enumerable: true,
});

/**
 * The base url of the axiom api.
 */
export declare const baseUrl: string | undefined;
Object.defineProperty(exports, 'baseUrl', {
  get() {
    return __config.get('baseUrl');
  },
  enumerable: true,
});
